### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by bravecharles** [randhana/Drowning-Detection-#12]
Hello,
I would like to know if you could share the dataset of this project please?

I am implementing a similar system with Conv3D, and I need information to train the model, that is, videos of underwater drowning situations,

I will be very grateful if you help me with this information.

Greetings and blessings

**Comment by randhana** [comment]
Here, I utilized a pre-trained model sourced from the internet. As such, I didn't create a custom dataset for training purposes.
