### ISSUE TITLE
how to train the model?

### ISSUE THREAD

**Issue by KiteA2022** [randhana/Drowning-Detection-#2]
how to train the model?

**Comment by randhana** [comment]
Training a Custom Model:
If you're interested in training a custom model for your specific requirements, you can refer to the YOLO (You Only Look Once) documentation. YOLO is a popular object detection framework that allows you to train custom models on your own dataset.

**Comment by randhana** [comment]
> how to train the model?

Training a Custom Model:
If you're interested in training a custom model for your specific requirements, you can refer to the YOLO (You Only Look Once) documentation. YOLO is a popular object detection framework that allows you to train custom models on your own dataset.
