### ISSUE TITLE
dataset is?

### ISSUE THREAD

**Issue by KiteA2022** [randhana/Drowning-Detection-#3]
dataset is?

**Comment by randhana** [comment]
> dataset is?

We utilized a pre-trained model for our drowning detection system, which means that we didn't create a custom dataset for training. Instead, we leveraged existing models that were already trained on extensive datasets containing various objects, including humans, in diverse water environments. This pre-trained model's capability to detect humans in different situations and lighting conditions significantly contributes to the accuracy of our system.
